### PR TITLE
[enh] selector: add a nslookup(host) function

### LINKED ISSUE #12: Selector: add a function nslookup.
The current selectors about the source IP and Host are
* IP
* Host

Behind a reverse proxy they are useless.

The HTTP header X-Forwarded-For allows to filter the real user IP:
```"filters": ["Header:X-Forwarded-For=<ip>```

In the [searx-docker](https://github.com/searx/searx-docker) project, there is this rule:
```yaml
    {
        "name": "searx.space",
        "filters": ["Header:X-Forwarded-For=(2001:41d0:8:de3::1|176.31.252.227)"],
        "stop": true,
        "actions": [{ "name": "log"}]
    },
```

It would useful to have something like this:
```yaml
    {
        "name": "searx.space",
        "filters": ["Header:X-Forwarded-For=nslookup(check.searx.space)"],
        "stop": true,
        "actions": [{ "name": "log"}]
    },
```

So even if at one point in time, ```check.searx.space``` resolves to different IPs, the rule would still work as expected.
The ```nslookup``` function can resolve the IPs addresses when filtron starts. The result of that function would be a regex similar to the first snippet.

Extend version: filtron resolves every day the IPs addresses without restart.

### PR DESCRIPTION
**Pull request by dalf**
fix https://github.com/asciimoo/filtron/issues/12

More or less a hack, but should be good enough for now.

### CODE REVIEW

**Review by asciimoo — CHANGES_REQUESTED** [review]
Nice!
Could you add a few words to the readme about the usage?

**Comment by dalf** [comment]
> Could you add a few words to the readme about the usage?

Done, feel free to rephrase / fix the syntax/grammar errors.

**Review by asciimoo — APPROVED** [review]
Great, thanks!

**Comment by unixfox** [comment]
Is it possible to publish a new binary with a new filtron release that contains this new feature?

**Comment by asciimoo** [comment]
Yup, I'm going to release it this weekend.

**Comment by asciimoo** [comment]
New release is available with binaries: https://github.com/asciimoo/filtron/releases/tag/v0.2.0

**Pull request merged**
